travis:
  secure:
    BINSTAR_TOKEN: jzQxH6GrBjSFhALeeAOLJSpYh8F1bG2rGj2hddv16ccv9T61ZArp37tBELKyZGlNZAuYefndtCXUb6h9xjO2xmhqEU3obPVeDSBETiAN5dK+cKEfFUBWWypb5ibWWCV8esl1Xgo0oUQ+DhBMt7G/7pPpKDtlwie/4GGvZCbJb3+nVQ3aQzG3GP7viSa4sN5qJPGN3jzUzWGbUMTkz4KVuzRfHTqm91ymsStnFmFLJCEj+PI1QyR0lWwKcI9VyzMUtZ4uvTAr3vBvAfPMRXpWKVuDEEDSmZKzg/r5vhHd/ql/Yd5/4nGy2vSDWtqPcdzK7dVRqPB4xYCYCoiKPuY9umrAlnW/SqnDhdzBU06kuu39ADigPzS0dDstv3+y+Ui48or9jp8p4UaDAD1vjmtX7bPJazlRx9a/yL0WGz2vBUVwWiEjAFnpVRScSLG2cis2yJ6nxyLcI5jcHOs/nanUeZfEj2It2B68L99XCm+LTchkfrEolr/bVFTLf/PsMnyw3+YjCQ+WjwmNwLrtHjmS0Yd7hocfW8Fi/14oQlblHu5TEv8kWMuligXm4xF2wK5KTkA1liv6l5Gr6EbI4xk1rqj9wyXzGUESFVoTD8wwTGj97kod+A/uYSMYQYeFnZprWmy67U9qsN67bGcuNmBIiXS0jsL4drIaAta9MiHsM20=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
